# Generated by Django 2.2.19 on 2022-08-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220813_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default='Группа "<django.db.models.fields.CharField>"'),
        ),
    ]
